# Generated by Django 3.2.7 on 2021-09-14 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.timezone)),
                ('followers', models.SmallIntegerField(default=0)),
                ('following', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
