# Generated by Django 3.2.7 on 2021-09-14 08:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', tinymce.models.HTMLField()),
                ('nickname', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('profilephoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
